[package]
name = "yt"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
chrono = "0.4"
chrono-tz = "0.10.4"
toml = "0.9.2"
serde = { version = "1.0.219", features = ["derive"] }
dirs = "6.0.0"
toml_edit = "0.23.2"
