[tasks.build-and-copy]
runner = "bash"
script = [
    "cargo build --release",
    "CRATE_NAME=$(grep '^name' Cargo.toml | cut -d '\"' -f2)",
    "cp ./target/release/$CRATE_NAME $HOME/workspace/tools"
]